spring:
  application:
    name: item-service
  rabbitmq:
    host:  192.168.206.128
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

 